### ISSUE TITLE
Description and link to where it is hosted

### ISSUE THREAD

**Issue by tamzi** [season6/swahiliDishes#3]
@ArvidQuarshie @cnzau @gitalry 
Please provide a description and a link to where it is being hosted.

**Comment by cnzau** [comment]
@gitalry please remember to close issues. Then u should giveus access to the admin dashboard for the site at bitballoon users

**Comment by gitalry** [comment]
sure

**Comment by gitalry** [comment]
admin to the link hosting is arvid, holler at him
